cask_args appdir: '/Applications'

tap "alexanderwillner/tap"
tap "caskformula/caskformula"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/science"
tap "homebrew/services"
tap "jmespath/jmespath"
tap "osx-cross/avr"
tap "px4/px4"
tap "railwaycat/emacsmacport"
tap "sass/sass"
tap "unbounce/taps"
tap "mas-cli/tap"

cask "xquartz"
brew "ack"
brew "gettext"
brew "openssl"
brew "python"
brew "icu4c"
brew "adwaita-icon-theme"
brew "ant"
brew "aspell"
brew "avrdude"
brew "awslogs"
brew "bash"
brew "bash-completion"
brew "bat"
brew "boost"
brew "closure-compiler"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "ctags"
brew "curl"
brew "dbus"
brew "dfu-programmer"
brew "dfu-util"
brew "dirmngr"
brew "editorconfig"
brew "gnutls"
brew "findutils", args: ["with-default-names"]
brew "fzf"
brew "gawk"
brew "git"
brew "git-extras"
brew "global"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-typist"
brew "pinentry"
brew "gnupg", link: false
brew "go"
brew "gpg-agent"
brew "libtool"
brew "grep"
brew "python@2"
brew "intltool"
brew "libxml2"
brew "jenv"
brew "jq"
brew "json-c"
brew "libyubikey"
brew "lzo"
brew "lzop"
brew "markdown"
brew "maven"
brew "md5sha1sum", link: false
brew "mas"
brew "mosh"
brew "mtr"
brew "mysql@5.6", link: false
brew "neovim"
brew "openssh"
brew "pandoc"
brew "parallel"
brew "perl"
brew "pngquant"
brew "pv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "screenfetch"
brew "shellcheck"
brew "shfmt"
brew "stow"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "watch"
brew "wget"
brew "yarn"
brew "zsh"
brew "lua"
brew "gcc"
brew "autojump"
brew "automake"
brew "tmux"
brew "fd"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-ctags", "with-emacs-icons-project-EmacsIcon3"]
brew "jmespath/jmespath/jp"
brew "osx-cross/avr/avr-gcc", args: ["with-gmp", "with-libmpc", "with-mpfr"], link: false
brew "osx-cross/avr/avr-gcc@7", link: true
brew "px4/px4/gcc-arm-none-eabi"
brew "px4/px4/gcc-arm-none-eabi-49"
brew "unbounce/taps/iidy"
brew "unbounce/taps/stack-toolkit"

cask "chromedriver"
cask "font-fantasquesansmono-nerd-font"
cask "font-firacode-nerd-font"
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "hammerspoon"
cask "unetbootin"
cask 'vagrant'
cask "vagrant-manager"
cask "virtualbox"


mas 'Fantastical 2', id: 975937182
mas 'YubiKey Personalization Tool', id: 638161122
mas 'iA Writer', id: 775737590
mas 'Airmail 3', id: 918858936
mas 'Deliveries', id: 924726344
mas 'OmniFocus', id: 1346203938
mas 'Pixelmator', id: 407963104
mas 'Twitterrific', id: 1289378661
