tap "d12frosted/emacs-plus"
tap "getantibody/tap"
tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jmespath/jmespath"
tap "mas-cli/tap"
tap "osx-cross/avr"
tap "px4/px4"
tap "teamookla/speedtest"
tap "unbounce/taps"
cask "adoptopenjdk8"
cask "xquartz"
brew "ack"
brew "openssl@1.1"
brew "python"
brew "adwaita-icon-theme"
brew "alure"
brew "ant"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "asdf"
brew "aspell"
brew "autojump"
brew "libelf"
brew "libusb"
brew "libusb-compat"
brew "libftdi0"
brew "avrdude"
brew "awscli"
brew "awslogs"
brew "bash"
brew "bash-completion"
brew "bat"
brew "boost"
brew "brotli"
brew "cabal-install"
brew "cabextract"
brew "clingo", link: false
brew "cloc"
brew "clojure"
brew "closure-compiler"
brew "cmake"
brew "cowsay"
brew "ctags", link: false
brew "curl"
brew "dfu-programmer"
brew "dfu-util"
brew "direnv"
brew "duc"
brew "editorconfig"
brew "exercism"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gawk"
brew "gifski"
brew "git"
brew "git-extras"
brew "global"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-typist"
brew "libksba"
brew "pinentry"
brew "gnupg", link: false
brew "go"
brew "grep"
brew "hlint"
brew "imagemagick"
brew "intltool"
brew "jansson"
brew "jenv"
brew "oniguruma"
brew "jq"
brew "json-c"
brew "kakoune"
brew "lcov"
brew "leiningen"
brew "libvterm"
brew "libxml2"
brew "libyubikey"
brew "lsd"
brew "lzop"
brew "make"
brew "markdown"
brew "mas"
brew "maven"
brew "md5sha1sum", link: false
brew "mosh"
brew "mtr"
brew "mysql@5.6"
brew "neovim"
brew "nethack"
brew "node"
brew "openssh"
brew "pandoc"
brew "parallel"
brew "perl"
brew "pipenv"
brew "pkg-config"
brew "pngquant"
brew "poppler"
brew "pth"
brew "pv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "ripgrep-all"
brew "rsync"
brew "screenfetch", args: ["HEAD"]
brew "shellcheck"
brew "shfmt"
brew "stow"
brew "tesseract-lang"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "zshdb"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-ctags", "with-dbus", "with-emacs-icons-project-EmacsIcon3", "without-spacemacs-icon"]
brew "getsentry/tools/sentry-cli"
brew "jmespath/jmespath/jp"
brew "osx-cross/avr/avr-gcc", link: false
brew "osx-cross/avr/avr-gcc@7", link: true
brew "px4/px4/gcc-arm-none-eabi"
brew "px4/px4/gcc-arm-none-eabi-49", link: false
brew "teamookla/speedtest/speedtest"
brew "unbounce/taps/iidy"
brew "unbounce/taps/stack-toolkit"
cask "adobe-acrobat-reader"
cask "adoptopenjdk11"
cask "bartender"
cask "discord"
cask "font-fantasquesansmono-nerd-font"
cask "font-fira-sans"
cask "font-firacode-nerd-font"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-hasklig"
cask "font-hasklig-nerd-font"
cask "font-ia-writer-duo"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-powerline"
cask "font-noto-serif"
cask "font-victor-mono"
cask "gpg-suite"
cask "hammerspoon"
cask "java"
cask "jitsi-meet"
cask "kap"
cask "karabiner-elements"
cask "keka"
cask "kekadefaultapp"
cask "meld"
cask "nordvpn"
cask "postico"
cask "resilio-sync"
cask "sequel-pro"
cask "textexpander"
cask "unetbootin"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
mas "1Password 7", id: 1333542190
mas "Airmail", id: 918858936
mas "Be Focused Pro", id: 961632517
mas "Better", id: 1121192229
mas "CCMenu", id: 603117688
mas "Deliveries", id: 924726344
mas "Drafts", id: 1435957248
mas "Endel", id: 1484348796
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Jira", id: 1475897096
mas "Keynote", id: 409183694
mas "Marked 2", id: 890031187
mas "MultiMarkdown Composer", id: 1275176220
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "OmniFocus", id: 1346203938
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Twitterrific", id: 1289378661
mas "Xcode", id: 497799835
mas "YubiKey Personalization Tool", id: 638161122
