tap "adoptopenjdk/openjdk"
tap "d12frosted/emacs-plus"
tap "getantibody/tap"
tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jmespath/jmespath"
tap "mas-cli/tap"
tap "osx-cross/avr"
tap "px4/px4"
tap "unbounce/taps"
cask "xquartz"
brew "ack"
brew "adwaita-icon-theme"
brew "alure"
brew "ant"
brew "aspell"
brew "autoconf"
brew "autojump"
brew "automake"
brew "libelf"
brew "libusb"
brew "libusb-compat"
brew "libftdi0"
brew "avrdude"
brew "awslogs"
brew "bash"
brew "bash-completion"
brew "bat"
brew "boost"
brew "brotli"
brew "cabextract"
brew "clingo", link: false
brew "cloc"
brew "closure-compiler"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "ctags", link: false
brew "curl"
brew "dfu-programmer"
brew "dfu-util"
brew "direnv"
brew "duc"
brew "editorconfig"
brew "fd"
brew "fzf"
brew "gawk"
brew "git"
brew "git-extras"
brew "global"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-typist"
brew "libksba"
brew "pinentry"
brew "gnupg"
brew "go"
brew "grep"
brew "intltool"
brew "jansson"
brew "jenv"
brew "oniguruma"
brew "jq"
brew "json-c"
brew "libxml2"
brew "libyubikey"
brew "lzop"
brew "markdown"
brew "mas"
brew "maven"
brew "md5sha1sum", link: false
brew "mosh"
brew "mtr"
brew "mysql@5.6"
brew "neovim"
brew "nethack"
brew "openssh"
brew "pandoc"
brew "parallel"
brew "perl"
brew "pipenv"
brew "pngquant"
brew "pth"
brew "pv"
brew "pyenv"
brew "python@2"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "screenfetch", args: ["HEAD"]
brew "shellcheck"
brew "shfmt"
brew "stow"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tmux"
brew "watch"
brew "wget"
brew "zlib"
brew "zsh"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-ctags", "with-dbus", "with-emacs-icons-project-EmacsIcon3", "with-no-titlebar", "without-spacemacs-icon"]
brew "getantibody/tap/antibody"
brew "getsentry/tools/sentry-cli"
brew "jmespath/jmespath/jp"
brew "osx-cross/avr/avr-gcc", link: false
brew "osx-cross/avr/avr-gcc@7", link: true
brew "px4/px4/gcc-arm-none-eabi"
brew "px4/px4/gcc-arm-none-eabi-49", link: false
brew "unbounce/taps/iidy"
brew "unbounce/taps/stack-toolkit"
cask "bartender"
cask "font-fantasquesansmono-nerd-font"
cask "font-fira-sans"
cask "font-firacode-nerd-font"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "gpg-suite"
cask "hammerspoon"
cask "java"
cask "karabiner-elements"
cask "keka"
cask "kekadefaultapp"
cask "nordvpn"
cask "resilio-sync"
cask "spectacle"
cask "textexpander"
cask "unetbootin"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
cask "adoptopenjdk/openjdk/adoptopenjdk11"
mas "1Password 7", id: 1333542190
mas "Be Focused Pro", id: 961632517
mas "Better", id: 1121192229
mas "Canary Mail", id: 1236045954
mas "CCMenu", id: 603117688
mas "Deliveries", id: 924726344
mas "Drafts", id: 1435957248
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Marked 2", id: 890031187
mas "MultiMarkdown Composer", id: 1275176220
mas "Numbers", id: 409203825
mas "OmniFocus", id: 1346203938
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Twitterrific", id: 1289378661
mas "Xcode", id: 497799835
mas "YubiKey Personalization Tool", id: 638161122
